### PR TITLE
create one_auth, one_user if create_oneadmin_auth_files is set to true

### PR DESCRIPTION
**Pull request by ghost**
i added this feature:
if i create pillar data like this:

```
...
    oneadmin:
      config:
        create_oneadmin_auth_files: True
        one_auth:
          contents: 'oneadmin:apassword'
        one_key:
          contents: 'apassword'
...
```

and have the changes applied to _user_oneadmin.sls, then a salt run on this formula on the controller would create one_auth and one_key, if they don't exist.
This is only helpful for initial installations on new servers, where these files don't exist.
As already discussed, changing contents of these files is not enough to change the  password, but on initial installation (bootstrapping of the database) the password in the database will be set with the content of these files, if they exist before the bootstrapping.

### CODE REVIEW

**Comment by arnisoph** [comment]
Hi!

Wouldn't it be already sufficient to define the following pillar data?

```
...
    oneadmin:
      config:
        manage:
          - one_auth
          - one_key
        one_auth:
          contents: 'oneadmin:apassword'
        one_key:
          contents: 'apassword'
...
```

**Comment by hoonetorg** [comment]
the difference to the config.manage block is the 

```
- unless: test -f {{ f.path }}
```

i want to achieve, that once the auth-files exist, they are not changed anymore by the formula
that is because:
you probably want to change the initial password after installation in the gui or in the database or with cli, and then you must change  the files afterwards manually.
if then the formula runs again, the auth-files are overwritten with the initial password

probably the unless could be put into the config.manage block with an additional switch
and then 

```
...
    oneadmin:
      config:
        manage:
          - one_auth
          - one_key
        one_auth:
          contents: 'oneadmin:apassword'
          createonly: true
        one_key:
          contents: 'apassword'
          createonly: true
...
```

**Comment by arnisoph** [comment]
@hoonetorg have you checked the replace parameter of `file.managed`?

http://docs.saltstack.com/en/develop/ref/states/all/salt.states.file.html#salt.states.file.managed

**Comment by arnisoph** [comment]
something like 

```
{% if 'replace' in f %}
    - replace: {{ f.replace }}
{% endif %}
```

could help.

**Comment by hoonetorg** [comment]
ok, only that i get you right
1. revert this commit
2. new commit:

```
diff --git a/opennebula/_user_oneadmin.sls b/opennebula/_user_oneadmin.sls
index b1f9cc7..e6a4e95 100644
--- a/opennebula/_user_oneadmin.sls
+++ b/opennebula/_user_oneadmin.sls
@@ -79,6 +79,9 @@ one_oneadmin_config_{{ c }}:
   file:
     - {{ f.ensure|default('managed') }}
     - name: {{ f.path }}
+  {% if 'replace' in f %}
+    - replace: {{ f.replace }}
+  {% endif %}
   {% if 'source' in f %}
     - source: {{ f.source }}
     - context: {{ f.context|default({}) }}
```

and change my local pillar data to

```
...
    oneadmin:
      config:
        manage:
          - one_auth
          - one_key
        one_auth:
          contents: 'oneadmin:apassword'
          replace: false
        one_key:
          contents: 'apassword'
          replace: false
...
```

If that's ok for you, i will immediately prepare and update the pull request to finish this thing up

**Comment by hoonetorg** [comment]
prepared, tested and pull request updated - hope you like it :)

**Comment by arnisoph** [comment]
:100: :+1:

**Pull request merged**
